version: '3.9'
services:
  oltp-db:
    image: postgres:14
    container_name: oltp-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oltp_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  dw-db:
    image: postgres:14
    container_name: dw-db
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dw_db
    volumes:
      - ./datawarehouse:/docker-entrypoint-initdb.d

  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow
    ports:
      - '8088:8080'
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./etl:/opt/airflow/dags
    command: ['webserver']

volumes:
  pg_data:
  dw_data:
